version: '3.8'

networks:
  app-network:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME}_network

services:
  minio:
    image: minio/minio:RELEASE.2024-01-13T07-53-03Z
    container_name: minio_server
    restart: unless-stopped
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      MINIO_REGION_NAME: ${AWS_REGION}
    volumes:
      - ./minio_data:/data
    networks:
      - app-network
    command: server /data --console-address ":9001"


  minio-setup:
    image: minio/mc:RELEASE.2024-01-13T08-44-48Z
    container_name: minio_setup
    networks:
      - app-network
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      MINIO_DEFAULT_BUCKET: ${AWS_BUCKET_NAME}
    volumes:
      - ./docker/minio/setup.sh:/setup.sh
    entrypoint: ["/bin/sh", "/setup.sh"]
    